### PR TITLE
Ability to allow cors on wildcard subdomain matches like so...

### PR DESCRIPTION
**Pull request by sjdirect**
-Ability to allow cors on wildcard subdomain matches like so...
-policy.Origins.Add("http://*.example.com"); //Allows all sudomains of example.com

### CODE REVIEW

**Comment by Eilon** [comment]
Closing because we ended up merging https://github.com/aspnet/CORS/pull/94. Thanks!

**Comment by PagesByZ** [comment]
Where do I add that?

[EnableCors(origins: "http://localhost:64, http://mysite:100, http://appset", headers: "*", methods: "*")] works for me but when I do the following, [EnableCors(origins: "http://localhost:64, http://mysite:100, http://appset, http://appset/mysubdomain", headers: "*", methods: "*")] nothing works.

How can I fix it please. Thanks.

**Comment by Eilon** [comment]
@kichalla can you help out?

**Comment by MienDev** [comment]
@PagesByZ  `http://appset/mysubdomain` is not a valid origin.   [rfc6454](https://tools.ietf.org/html/rfc6454) for your reference.

**Pull request closed without merging**
